annotations:
  category: CMS
apiVersion: v2
appVersion: 5.5.1
dependencies:
  - condition: mariadb.enabled
    name: mariadb
    repository: https://charts.bitnami.com/bitnami
    tags:
      - wordpress-database
    version: 7.x.x
description: Web publishing platform for building blogs and websites.
engine: gotpl
home: https://github.com/bitnami/charts/tree/master/bitnami/wordpress
icon: https://bitnami.com/assets/stacks/wordpress/img/wordpress-stack-220x234.png
keywords:
  - wordpress
  - cms
  - blog
  - http
  - web
  - application
  - php
maintainers:
  - email: containers@bitnami.com
    name: Bitnami
name: wordpress
sources:
  - https://github.com/bitnami/bitnami-docker-wordpress
  - http://www.wordpress.com/
version: 10.0.0
