apiVersion: v2
name: wordpress
version: 10.0.0
appVersion: 5.5.1
description: Web publishing platform for building blogs and websites.
icon: https://bitnami.com/assets/stacks/wordpress/img/wordpress-stack-220x234.png
keywords:
  - wordpress
  - cms
  - blog
  - http
  - web
  - application
  - php
home: https://github.com/bitnami/charts/tree/master/bitnami/wordpress
sources:
  - https://github.com/bitnami/bitnami-docker-wordpress
  - http://www.wordpress.com/
maintainers:
  - name: Bitnami
    email: containers@bitnami.com
engine: gotpl
annotations:
  category: CMS
dependencies:
  - name: mariadb
    version: 7.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.enabled
    tags:
      - wordpress-database
